# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-23 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
        ('material', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentinfo',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user.GuestProfile', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='commentinfo',
            name='parent_comment',
            field=models.ForeignKey(blank=True, help_text='根评论', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_comment', to='comment.CommentInfo', verbose_name='根评论'),
        ),
        migrations.AddField(
            model_name='commentinfo',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.PostBaseInfo', verbose_name='所属文章'),
        ),
        migrations.AddField(
            model_name='commentinfo',
            name='reply_to_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='be_comments', to='user.GuestProfile', verbose_name='被回复人'),
        ),
        migrations.AddField(
            model_name='commentinfo',
            name='reply_to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_comment', to='comment.CommentInfo', verbose_name='父级评论'),
        ),
        migrations.AddField(
            model_name='commentdetail',
            name='comment_info',
            field=models.OneToOneField(blank=True, help_text='基本信息', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='comment.CommentInfo', verbose_name='基本信息'),
        ),
    ]
