# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-23 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_content', models.TextField(help_text='原始内容', verbose_name='原始内容')),
                ('formatted_content', models.TextField(help_text='处理后内容', verbose_name='处理后内容')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name_plural': '图书详情列表',
                'verbose_name': '图书详情',
            },
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('postbaseinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='material.PostBaseInfo')),
                ('is_reading', models.BooleanField(default=False, help_text='是否正在阅读', verbose_name='是否正在阅读')),
                ('read_precentage', models.FloatField(blank=True, default=0.0, help_text='阅读进度', null=True, verbose_name='阅读进度')),
                ('douban_type', models.CharField(blank=True, choices=[('book', '图书'), ('movie', '电影')], help_text='豆瓣资源类型', max_length=255, null=True, verbose_name='豆瓣资源类型')),
                ('douban_id', models.CharField(blank=True, help_text='豆瓣资源ID', max_length=255, null=True, verbose_name='豆瓣资源ID')),
                ('douban_infos', models.TextField(blank=True, help_text='豆瓣信息', null=True, verbose_name='豆瓣信息')),
                ('book_isbn10', models.CharField(blank=True, help_text='isbn10', max_length=255, null=True, verbose_name='isbn10')),
                ('book_isbn13', models.CharField(blank=True, help_text='isbn13', max_length=255, null=True, verbose_name='isbn13')),
                ('book_name', models.CharField(blank=True, help_text='书名', max_length=255, null=True, verbose_name='书名')),
                ('book_origin_name', models.CharField(blank=True, help_text='本书原始名', max_length=100, null=True, verbose_name='本书原始名')),
                ('book_image', models.URLField(blank=True, help_text='本书图片', null=True, verbose_name='本书图片')),
                ('book_author', models.CharField(blank=True, help_text='本书作者', max_length=255, null=True, verbose_name='本书作者')),
                ('book_tags', models.CharField(blank=True, help_text='本书标签', max_length=255, null=True, verbose_name='本书标签')),
                ('book_rating', models.CharField(blank=True, help_text='本书豆瓣评分', max_length=10, null=True, verbose_name='本书豆瓣评分')),
                ('book_publisher', models.CharField(blank=True, help_text='出版社', max_length=255, null=True, verbose_name='出版社')),
                ('publish_date', models.CharField(blank=True, help_text='出版日期', max_length=30, null=True, verbose_name='出版日期')),
                ('book_pages', models.CharField(blank=True, help_text='总页数', max_length=20, null=True, verbose_name='总页数')),
                ('book_url', models.URLField(blank=True, help_text='本书豆瓣链接', null=True, verbose_name='本书豆瓣链接')),
                ('book_api', models.URLField(blank=True, help_text='本书API链接', null=True, verbose_name='本书API链接')),
                ('is_update_douban_info', models.BooleanField(default=False, help_text='会自动更新所有未填写的豆瓣信息', verbose_name='是否更新')),
            ],
            options={
                'verbose_name_plural': '图书列表',
                'verbose_name': '图书',
            },
            bases=('material.postbaseinfo',),
        ),
        migrations.CreateModel(
            name='BookNoteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_content', models.TextField(help_text='原始内容', verbose_name='原始内容')),
                ('formatted_content', models.TextField(help_text='处理后内容', verbose_name='处理后内容')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name_plural': '图书笔记详情列表',
                'verbose_name': '图书笔记详情',
            },
        ),
        migrations.CreateModel(
            name='BookNoteInfo',
            fields=[
                ('postbaseinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='material.PostBaseInfo')),
                ('note_type', models.CharField(blank=True, choices=[('1', '一级'), ('2', '二级'), ('3', '三级')], help_text='笔记级别', max_length=20, null=True, verbose_name='笔记级别')),
                ('is_reading', models.BooleanField(default=False, help_text='是否正在阅读', verbose_name='是否正在阅读')),
                ('is_completed', models.BooleanField(default=False, help_text='是否读完', verbose_name='是否读完')),
                ('is_noted', models.BooleanField(default=False, help_text='笔记是否完成', verbose_name='笔记是否完成')),
                ('book', models.ForeignKey(blank=True, help_text='图书', null=True, on_delete=django.db.models.deletion.CASCADE, to='book.BookInfo', verbose_name='图书')),
                ('parent_note', models.ForeignKey(blank=True, help_text='父笔记', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_note', to='book.BookNoteInfo', verbose_name='父笔记')),
            ],
            options={
                'verbose_name_plural': '图书笔记列表',
                'verbose_name': '图书笔记',
            },
            bases=('material.postbaseinfo',),
        ),
        migrations.CreateModel(
            name='BookResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('download', models.FileField(upload_to='book/resource/%Y/%m', verbose_name='资源文件')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.BookInfo', verbose_name='图书')),
            ],
            options={
                'verbose_name_plural': '图书资源',
                'verbose_name': '图书资源',
            },
        ),
        migrations.AddField(
            model_name='booknotedetail',
            name='book_note_info',
            field=models.ForeignKey(blank=True, help_text='内容', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='book.BookNoteInfo', verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='bookdetail',
            name='book_info',
            field=models.ForeignKey(blank=True, help_text='内容', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='book.BookInfo', verbose_name='内容'),
        ),
    ]
