# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-26 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0009_auto_20180126_1440'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknoteinfo',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.BookInfo', verbose_name='图书'),
        ),
        migrations.AddField(
            model_name='booknoteinfo',
            name='category_type',
            field=models.CharField(blank=True, choices=[('1', '一级'), ('2', '二级'), ('3', '三级')], help_text='类目级别', max_length=20, null=True, verbose_name='类目级别'),
        ),
        migrations.AddField(
            model_name='booknoteinfo',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='book.BookNoteInfo', verbose_name='父类目级别'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='douban_id',
            field=models.CharField(blank=True, help_text='豆瓣资源ID', max_length=255, null=True, verbose_name='豆瓣资源ID'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='douban_type',
            field=models.CharField(blank=True, choices=[('book', '图书'), ('movie', '电影')], help_text='豆瓣资源类型', max_length=255, null=True, verbose_name='豆瓣资源类型'),
        ),
        migrations.AlterField(
            model_name='bookresource',
            name='download',
            field=models.FileField(upload_to='book/resource/%Y/%m', verbose_name='资源文件'),
        )
    ]
