# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-27 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='is_reading',
            field=models.BooleanField(default=False, help_text='是否正在阅读', verbose_name='是否正在阅读'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='read_precentage',
            field=models.FloatField(blank=True, default=0.0, help_text='阅读进度', null=True, verbose_name='阅读进度'),
        ),
    ]
