# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-26 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0009_auto_20180126_1440'),
        ('book', '0002_auto_20180126_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookchapter',
            name='booknoteinfo_ptr',
        ),
        migrations.RemoveField(
            model_name='booksection',
            name='booknoteinfo_ptr',
        ),
        migrations.RemoveField(
            model_name='booksection',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='booknoteinfo',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='booknoteinfo',
            name='parent_category',
        ),
        migrations.AddField(
            model_name='booknoteinfo',
            name='note_type',
            field=models.CharField(blank=True, choices=[('1', '一级'), ('2', '二级'), ('3', '三级')], help_text='笔记级别', max_length=20, null=True, verbose_name='笔记级别'),
        ),
        migrations.AddField(
            model_name='booknoteinfo',
            name='parent_note',
            field=models.ForeignKey(blank=True, help_text='父笔记', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_note', to='book.BookNoteInfo', verbose_name='父笔记'),
        ),
        migrations.DeleteModel(
            name='BookChapter',
        ),
        migrations.DeleteModel(
            name='BookSection',
        ),
    ]
