# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-10 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20180227_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknoteinfo',
            name='book',
            field=models.ForeignKey(blank=True, help_text='图书', null=True, on_delete=django.db.models.deletion.CASCADE, to='book.BookInfo', verbose_name='图书'),
        ),
    ]
