# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-26 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20180126_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknoteinfo',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='是否读完', verbose_name='是否读完'),
        ),
        migrations.AddField(
            model_name='booknoteinfo',
            name='is_noted',
            field=models.BooleanField(default=False, help_text='笔记是否完成', verbose_name='笔记是否完成'),
        ),
        migrations.AddField(
            model_name='booknoteinfo',
            name='is_reading',
            field=models.BooleanField(default=False, help_text='是否正在阅读', verbose_name='是否正在阅读'),
        ),
    ]
