# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-23 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20180223_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetail',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='booknotedetail',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间'),
        ),
    ]
