# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-23 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20180223_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdetail',
            name='douban_infos',
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='douban_infos',
            field=models.TextField(blank=True, help_text='豆瓣信息', null=True, verbose_name='豆瓣信息'),
        ),
    ]
