# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-23 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20180223_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdetail',
            name='is_update_douban_info',
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='is_update_douban_info',
            field=models.BooleanField(default=False, help_text='会自动更新所有未填写的豆瓣信息', verbose_name='是否更新'),
        ),
    ]
