# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-27 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_bookinfo_douban_infos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='isbn10',
            new_name='book_isbn10',
        ),
        migrations.RenameField(
            model_name='bookinfo',
            old_name='isbn13',
            new_name='book_isbn13',
        ),
        migrations.RenameField(
            model_name='bookinfo',
            old_name='pages',
            new_name='book_pages',
        ),
        migrations.RenameField(
            model_name='bookinfo',
            old_name='publisher',
            new_name='book_publisher',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='douban_infos',
        ),
        migrations.AddField(
            model_name='bookdetail',
            name='is_update_douban_info',
            field=models.BooleanField(default=False, help_text='是否更新豆瓣信息', verbose_name='是否更新'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='book_api',
            field=models.URLField(blank=True, help_text='本书API链接', null=True, verbose_name='本书API链接'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='book_image',
            field=models.URLField(blank=True, help_text='本书图片', null=True, verbose_name='本书图片'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='book_origin_name',
            field=models.CharField(blank=True, help_text='本书原始名', max_length=20, null=True, verbose_name='本书原始名'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='book_tags',
            field=models.CharField(blank=True, help_text='本书标签', max_length=20, null=True, verbose_name='本书标签'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='book_url',
            field=models.URLField(blank=True, help_text='本书豆瓣链接', null=True, verbose_name='本书豆瓣链接'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='publish_date',
            field=models.CharField(blank=True, help_text='出版日期', max_length=20, null=True, verbose_name='出版日期'),
        ),
    ]
