# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-27 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20180127_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='book_origin_name',
            field=models.CharField(blank=True, help_text='本书原始名', max_length=100, null=True, verbose_name='本书原始名'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='book_tags',
            field=models.CharField(blank=True, help_text='本书标签', max_length=255, null=True, verbose_name='本书标签'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='publish_date',
            field=models.CharField(blank=True, help_text='出版日期', max_length=30, null=True, verbose_name='出版日期'),
        ),
    ]
