# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-29 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20180127_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='book_rating',
            field=models.CharField(blank=True, help_text='本书豆瓣评分', max_length=10, null=True, verbose_name='本书豆瓣评分'),
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='is_update_douban_info',
            field=models.BooleanField(default=False, help_text='会自动更新所有未填写的豆瓣信息', verbose_name='是否更新'),
        ),
    ]
