# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-01 09:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=100, verbose_name='标题')),
                ('subtitle', models.CharField(blank=True, help_text='子标题', max_length=100, null=True, verbose_name='子标题')),
                ('abstract', models.CharField(blank=True, help_text='摘要', max_length=255, null=True, verbose_name='摘要')),
                ('desc', models.CharField(blank=True, help_text='简介', max_length=255, null=True, verbose_name='简介')),
                ('author', models.CharField(blank=True, help_text='作者', max_length=20, null=True, verbose_name='作者')),
                ('click_num', models.IntegerField(default=0, help_text='点击数', verbose_name='点击数')),
                ('like_num', models.IntegerField(default=0, help_text='点击数', verbose_name='点赞数')),
                ('comment_num', models.IntegerField(default=0, help_text='评论数', verbose_name='评论数')),
                ('front_image', models.ImageField(blank=True, help_text='封面图', null=True, upload_to='article/images', verbose_name='封面图')),
                ('front_image_type', models.CharField(choices=[('0', '无'), ('1', '小图'), ('2', '大图')], help_text='封面图类别', max_length=20, verbose_name='封面图类别')),
                ('is_hot', models.BooleanField(default=False, help_text='是否热门', verbose_name='是否热门')),
                ('is_recommend', models.BooleanField(default=False, help_text='是否推荐', verbose_name='是否推荐')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('category', models.ForeignKey(help_text='类别', on_delete=django.db.models.deletion.CASCADE, to='material.MaterialCategory', verbose_name='类别')),
            ],
            options={
                'verbose_name': '文章基本信息',
                'verbose_name_plural': '文章基本信息',
            },
        ),
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('album', models.ForeignKey(help_text='图集', on_delete=django.db.models.deletion.CASCADE, to='album.AlbumInfo', verbose_name='图集')),
                ('picture', models.ForeignKey(help_text='图片', on_delete=django.db.models.deletion.CASCADE, to='material.MaterialPicture', verbose_name='图片')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('album', models.ForeignKey(help_text='图集', on_delete=django.db.models.deletion.CASCADE, to='album.AlbumInfo', verbose_name='图集')),
                ('tag', models.ForeignKey(help_text='标签', on_delete=django.db.models.deletion.CASCADE, to='material.MaterialTag', verbose_name='标签')),
            ],
        ),
        migrations.AddField(
            model_name='albuminfo',
            name='pictures',
            field=models.ManyToManyField(help_text='图片', through='album.AlbumPhoto', to='material.MaterialPicture', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='albuminfo',
            name='tags',
            field=models.ManyToManyField(help_text='标签', through='album.AlbumTag', to='material.MaterialTag', verbose_name='标签'),
        ),
    ]
