# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-23 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumInfo',
            fields=[
                ('postbaseinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='material.PostBaseInfo')),
            ],
            options={
                'verbose_name_plural': '图集列表',
                'verbose_name': '图集',
            },
            bases=('material.postbaseinfo',),
        ),
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间')),
                ('album', models.ForeignKey(help_text='图集', on_delete=django.db.models.deletion.CASCADE, to='album.AlbumInfo', verbose_name='图集')),
                ('picture', models.ForeignKey(help_text='图片', on_delete=django.db.models.deletion.CASCADE, to='material.MaterialPicture', verbose_name='图片')),
            ],
            options={
                'verbose_name_plural': '图集图片列表',
                'verbose_name': '图集图片',
            },
        ),
        migrations.AddField(
            model_name='albuminfo',
            name='pictures',
            field=models.ManyToManyField(help_text='图片', through='album.AlbumPhoto', to='material.MaterialPicture', verbose_name='图片'),
        ),
    ]
