# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albuminfo',
            name='post_type',
            field=models.CharField(choices=[('0', 'article'), ('1', 'album'), ('2', 'movie')], default='1', help_text='POST类别', max_length=10, verbose_name='POST类别'),
        ),
    ]
