# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 07:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=100, verbose_name='标题')),
                ('image', models.ImageField(help_text='图片', upload_to='banner/%y/%m', verbose_name='图片')),
                ('url', models.URLField(help_text='链接', verbose_name='链接')),
                ('index', models.IntegerField(default=0, help_text='顺序', verbose_name='顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='MaterialCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(help_text='设备', max_length=30, verbose_name='设备')),
                ('version', models.CharField(help_text='版本', max_length=100, verbose_name='版本')),
                ('environment', models.ImageField(help_text='环境', upload_to='banner/%y/%m', verbose_name='环境')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '相机型号',
                'verbose_name_plural': '相机型号',
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code')),
                ('desc', models.TextField(default='', help_text='类别描述', verbose_name='类别描述')),
                ('image', models.ImageField(default='images/default.png', help_text='图片', upload_to='images/class/')),
                ('category_type', models.CharField(choices=[('1', '一级类目'), ('2', '二级类目'), ('3', '三级类目')], help_text='类目级别', max_length=20, verbose_name='类目级别')),
                ('is_tab', models.BooleanField(default=False, help_text='是否导航', verbose_name='是否导航')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='material.MaterialCategory', verbose_name='父类目级别')),
            ],
            options={
                'verbose_name': '素材类别',
                'verbose_name_plural': '素材类别',
            },
        ),
        migrations.CreateModel(
            name='MaterialMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='名称', max_length=30, verbose_name='名称')),
                ('desc', models.CharField(help_text='简介', max_length=100, verbose_name='简介')),
                ('image', models.ImageField(help_text='图片', upload_to='banner/%y/%m', verbose_name='图片')),
                ('url', models.URLField(help_text='链接', verbose_name='链接')),
                ('experience', models.FloatField(default=0, help_text='熟练度', verbose_name='熟练度')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
            },
        ),
        migrations.CreateModel(
            name='MaterialPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=100, verbose_name='标题')),
                ('subtitle', models.CharField(blank=True, help_text='子标题', max_length=100, null=True, verbose_name='子标题')),
                ('abstract', models.CharField(blank=True, help_text='摘要', max_length=255, null=True, verbose_name='摘要')),
                ('desc', models.CharField(blank=True, help_text='简介', max_length=255, null=True, verbose_name='简介')),
                ('image', models.ImageField(default='images/default.png', help_text='图片', upload_to='images/%Y/%m', verbose_name='图片')),
                ('link', models.URLField(blank=True, help_text='链接', null=True, verbose_name='链接')),
                ('camera', models.ForeignKey(blank=True, help_text='拍摄相机', null=True, on_delete=django.db.models.deletion.CASCADE, to='material.MaterialCamera', verbose_name='拍摄相机')),
            ],
            options={
                'verbose_name': '素材图片',
                'verbose_name_plural': '素材图片',
            },
        ),
        migrations.CreateModel(
            name='MaterialSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='名称', max_length=30, verbose_name='名称')),
                ('desc', models.CharField(help_text='简介', max_length=100, verbose_name='简介')),
                ('image', models.ImageField(help_text='图片', upload_to='banner/%y/%m', verbose_name='图片')),
                ('url', models.URLField(help_text='链接', verbose_name='链接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '社交平台',
                'verbose_name_plural': '社交平台',
            },
        ),
        migrations.CreateModel(
            name='MaterialTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='标签名', max_length=30, verbose_name='标签名')),
                ('subname', models.CharField(help_text='标签别名', max_length=30, verbose_name='标签别名')),
                ('color', models.CharField(choices=[('blue', '蓝色'), ('green', '绿色'), ('red', '红色'), ('yellow', '黄色')], default='blue', help_text='颜色', max_length=20, verbose_name='颜色')),
                ('category', models.ForeignKey(blank=True, help_text='类别', null=True, on_delete=django.db.models.deletion.CASCADE, to='material.MaterialCategory', verbose_name='类别')),
            ],
            options={
                'verbose_name': '素材标签',
                'verbose_name_plural': '素材标签',
            },
        ),
    ]
