# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-24 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcategory',
            name='index',
            field=models.IntegerField(default=0, help_text='排序', verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='materialcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否激活', verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='materialcategory',
            name='is_tab',
            field=models.BooleanField(default=True, help_text='是否导航', verbose_name='是否导航'),
        ),
    ]
