# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-23 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialbanner',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='materialcamera',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='materialcommentinfo',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='materiallicense',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='materialmaster',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='materialpicture',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='materialsocial',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='materialtag',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='postbaseinfo',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间'),
        ),
    ]
