# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(default='1', help_text='类别', on_delete=django.db.models.deletion.CASCADE, to='material.MaterialCategory', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='materialcamera',
            name='environment',
            field=models.CharField(help_text='环境', max_length=200, verbose_name='环境'),
        ),
        migrations.AlterField(
            model_name='materialcamera',
            name='version',
            field=models.CharField(help_text='版本', max_length=200, verbose_name='版本'),
        ),
    ]
