# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-26 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postbaseinfo',
            options={'verbose_name': '所有博文', 'verbose_name_plural': '所有博文列表'},
        ),
        migrations.AddField(
            model_name='postbaseinfo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否激活', verbose_name='是否激活'),
        ),
        migrations.AddField(
            model_name='postbaseinfo',
            name='is_banner',
            field=models.BooleanField(default=False, help_text='是否是Banner', verbose_name='是否是Banner'),
        ),
    ]
