# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcategory',
            name='subname',
            field=models.CharField(default='', help_text='别名', max_length=30, verbose_name='别名'),
        ),
        migrations.AlterField(
            model_name='materialcategory',
            name='code',
            field=models.CharField(default='', help_text='code', max_length=30, verbose_name='code'),
        ),
    ]
