# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-10 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20180430_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialcommentdetail',
            name='comment_info',
        ),
        migrations.RemoveField(
            model_name='materialcommentinfo',
            name='author',
        ),
        migrations.RemoveField(
            model_name='materialcommentinfo',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='materialcommentinfo',
            name='post',
        ),
        migrations.RemoveField(
            model_name='materialcommentinfo',
            name='reply_to_author',
        ),
        migrations.RemoveField(
            model_name='materialcommentinfo',
            name='reply_to_comment',
        ),
        migrations.DeleteModel(
            name='MaterialCommentDetail',
        ),
        migrations.DeleteModel(
            name='MaterialCommentInfo',
        ),
    ]
