# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20171222_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialbanner',
            options={'verbose_name': '轮播图', 'verbose_name_plural': '轮播图列表'},
        ),
        migrations.AlterModelOptions(
            name='materialcamera',
            options={'verbose_name': '相机型号', 'verbose_name_plural': '相机型号列表'},
        ),
        migrations.AlterModelOptions(
            name='materialcategory',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类列表'},
        ),
        migrations.AlterModelOptions(
            name='materiallicense',
            options={'verbose_name': '授权', 'verbose_name_plural': '授权列表'},
        ),
        migrations.AlterModelOptions(
            name='materialmaster',
            options={'verbose_name': '技能', 'verbose_name_plural': '技能列表'},
        ),
        migrations.AlterModelOptions(
            name='materialpicture',
            options={'verbose_name': '图片', 'verbose_name_plural': '图片列表'},
        ),
        migrations.AlterModelOptions(
            name='materialsocial',
            options={'verbose_name': '社交平台', 'verbose_name_plural': '社交平台列表'},
        ),
        migrations.AlterModelOptions(
            name='materialtag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签列表'},
        ),
        migrations.AlterModelOptions(
            name='posttag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签列表'},
        ),
        migrations.AddField(
            model_name='postbaseinfo',
            name='post_type',
            field=models.CharField(blank=True, choices=[('0', 'article'), ('1', 'album'), ('2', 'movie')], help_text='POST类别', max_length=10, null=True, verbose_name='POST类别'),
        ),
    ]
