# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-17 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20180524_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialpicture',
            old_name='abstract',
            new_name='en_desc',
        ),
        migrations.RenameField(
            model_name='materialpicture',
            old_name='subtitle',
            new_name='en_title',
        ),
        migrations.RemoveField(
            model_name='materialcategory',
            name='subname',
        ),
        migrations.RemoveField(
            model_name='materiallicense',
            name='subname',
        ),
        migrations.RemoveField(
            model_name='materialtag',
            name='subname',
        ),
        migrations.RemoveField(
            model_name='postbaseinfo',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='postbaseinfo',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='materialbanner',
            name='en_title',
            field=models.CharField(blank=True, help_text='标题', max_length=100, null=True, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='materialcategory',
            name='en_desc',
            field=models.TextField(blank=True, help_text='类别描述', null=True, verbose_name='类别描述'),
        ),
        migrations.AddField(
            model_name='materialcategory',
            name='en_name',
            field=models.CharField(blank=True, help_text='英文名', max_length=30, null=True, verbose_name='英文名'),
        ),
        migrations.AddField(
            model_name='materiallicense',
            name='en_desc',
            field=models.CharField(blank=True, help_text='简介', max_length=255, null=True, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='materiallicense',
            name='en_name',
            field=models.CharField(blank=True, help_text='英文名', max_length=30, null=True, verbose_name='英文名'),
        ),
        migrations.AddField(
            model_name='materialmaster',
            name='en_desc',
            field=models.CharField(blank=True, help_text='简介', max_length=100, null=True, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='materialmaster',
            name='en_name',
            field=models.CharField(blank=True, help_text='名称', max_length=30, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='materialsocial',
            name='en_desc',
            field=models.CharField(blank=True, help_text='简介', max_length=100, null=True, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='materialsocial',
            name='en_name',
            field=models.CharField(blank=True, help_text='名称', max_length=30, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='materialtag',
            name='en_name',
            field=models.CharField(blank=True, help_text='英文名', max_length=30, null=True, verbose_name='英文名'),
        ),
        migrations.AddField(
            model_name='postbaseinfo',
            name='en_desc',
            field=models.CharField(blank=True, help_text='英文简介', max_length=255, null=True, verbose_name='英文简介'),
        ),
        migrations.AddField(
            model_name='postbaseinfo',
            name='en_title',
            field=models.CharField(blank=True, help_text='英文标题', max_length=100, null=True, verbose_name='英文标题'),
        ),
        migrations.AlterField(
            model_name='materialcategory',
            name='desc',
            field=models.TextField(blank=True, help_text='类别描述', null=True, verbose_name='类别描述'),
        ),
        migrations.AlterField(
            model_name='materialmaster',
            name='desc',
            field=models.CharField(blank=True, help_text='简介', max_length=100, null=True, verbose_name='简介'),
        ),
    ]
