# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-25 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20180223_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialcategory',
            old_name='category_type',
            new_name='category_level',
        ),
        migrations.AlterField(
            model_name='materialcategory',
            name='code',
            field=models.CharField(choices=[('articles', '文章总分类'), ('articles/category', '文章分类'), ('albums', '图集总分类'), ('albums/category', '图集分类'), ('movies', '电影总分类'), ('movies/category', '电影分类'), ('readings', '阅读总分类'), ('readings/category', '阅读分类'), ('books', '书籍总分类'), ('books/category', '书籍分类'), ('book/notes', '阅读笔记总分类'), ('book/notes/category', '阅读笔记分类')], help_text='用于配置路由跳转', max_length=30, verbose_name='路由编码'),
        ),
    ]
