# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-27 07:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20171226_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCommentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_content', models.TextField(help_text='原始内容', verbose_name='原始内容')),
                ('formatted_content', models.TextField(help_text='处理后内容', verbose_name='处理后内容')),
                ('update_time', models.DateTimeField(help_text='修改时间', verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '评论详细信息',
                'verbose_name_plural': '评论详细信息列表',
            },
        ),
        migrations.CreateModel(
            name='MaterialCommentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, help_text='作者', max_length=20, null=True, verbose_name='作者')),
                ('comment_level', models.IntegerField(default=0, help_text='评论级别', verbose_name='评论级别')),
                ('like_num', models.IntegerField(default=0, help_text='点赞数', verbose_name='点赞数')),
                ('unlike_num', models.IntegerField(default=0, help_text='反对数', verbose_name='反对数')),
                ('comment_num', models.IntegerField(default=0, help_text='评论数', verbose_name='评论数')),
                ('is_hot', models.BooleanField(default=False, help_text='是否热门', verbose_name='是否热门')),
                ('is_recommend', models.BooleanField(default=False, help_text='是否推荐', verbose_name='是否推荐')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活', verbose_name='是否激活')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('parent_comment', models.ForeignKey(blank=True, help_text='根评论', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_comment', to='material.MaterialCommentInfo', verbose_name='根评论')),
            ],
            options={
                'verbose_name': '评论基本信息',
                'verbose_name_plural': '评论基本信息列表',
            },
        ),
        migrations.AddField(
            model_name='postbaseinfo',
            name='license',
            field=models.ForeignKey(blank=True, help_text='版权', null=True, on_delete=django.db.models.deletion.CASCADE, to='material.MaterialLicense', verbose_name='版权'),
        ),
        migrations.AddField(
            model_name='materialcommentinfo',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.PostBaseInfo', verbose_name='所属文章'),
        ),
        migrations.AddField(
            model_name='materialcommentinfo',
            name='reply_to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_comment', to='material.MaterialCommentInfo', verbose_name='父级评论'),
        ),
        migrations.AddField(
            model_name='materialcommentdetail',
            name='comment_info',
            field=models.OneToOneField(blank=True, help_text='基本信息', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='material.MaterialCommentInfo', verbose_name='基本信息'),
        ),
    ]
