# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20171208_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Master',
            new_name='MaterialMaster',
        ),
        migrations.RenameModel(
            old_name='Social',
            new_name='MaterialSocial',
        ),
    ]
