# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-25 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20180225_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialcategory',
            old_name='code',
            new_name='category_type',
        ),
    ]
