# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-28 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20171227_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcommentinfo',
            name='reply_to_author',
            field=models.CharField(blank=True, help_text='被回复人', max_length=20, null=True, verbose_name='被回复人'),
        ),
        migrations.AlterField(
            model_name='materiallicense',
            name='link',
            field=models.URLField(blank=True, help_text='版权参考链接', null=True, verbose_name='版权参考链接'),
        ),
        migrations.AlterField(
            model_name='materiallicense',
            name='name',
            field=models.CharField(help_text='版权名', max_length=30, verbose_name='版权名'),
        ),
        migrations.AlterField(
            model_name='materiallicense',
            name='subname',
            field=models.CharField(help_text='版权别名', max_length=30, verbose_name='版权别名'),
        ),
    ]
