# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_auto_20171208_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtag',
            name='color',
            field=models.CharField(choices=[('blue', '蓝色'), ('green', '绿色'), ('red', '红色'), ('yellow', '黄色')], default='blue', help_text='颜色', max_length=20, verbose_name='颜色'),
        ),
    ]
