# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-28 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_auto_20171228_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcommentdetail',
            name='formatted_content',
            field=models.TextField(blank=True, help_text='处理后内容', null=True, verbose_name='处理后内容'),
        ),
    ]
