# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-24 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_postbaseinfo_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbaseinfo',
            name='front_image',
            field=models.ImageField(blank=True, help_text='大图833*217，小图243*207', null=True, upload_to='post/image/%y/%m', verbose_name='封面图'),
        ),
    ]
