# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-28 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_auto_20171228_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcommentinfo',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user.GuestProfile', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='materialcommentinfo',
            name='reply_to_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='be_comments', to='user.GuestProfile', verbose_name='被回复人'),
        ),
    ]
