# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_materialtag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcategory',
            name='images',
            field=models.ImageField(default='images/default.png', help_text='图片', upload_to='images/%Y/%m'),
        ),
    ]
