# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-04 03:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_auto_20171228_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='postbaseinfo',
            name='browse_password',
            field=models.CharField(blank=True, help_text='浏览密码', max_length=10, null=True, verbose_name='浏览密码'),
        ),
        migrations.AddField(
            model_name='postbaseinfo',
            name='browse_password_encrypt',
            field=models.CharField(blank=True, help_text='浏览密码加密', max_length=10, null=True, verbose_name='浏览密码加密'),
        ),
        migrations.AlterField(
            model_name='materialcommentdetail',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='修改时间', null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='materiallicense',
            name='color',
            field=models.CharField(choices=[('#878D99', '灰色'), ('#409EFF', '蓝色'), ('#67C23A', '绿色'), ('#EB9E05', '黄色'), ('#FA5555', '红色')], default='blue', help_text='颜色', max_length=20, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='materialtag',
            name='color',
            field=models.CharField(choices=[('blue', '蓝色'), ('green', '绿色'), ('red', '红色'), ('orange', '黄色')], default='blue', help_text='颜色', max_length=20, verbose_name='颜色'),
        ),
    ]
