# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-26 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_auto_20180112_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbaseinfo',
            name='post_type',
            field=models.CharField(blank=True, choices=[('article', '文章'), ('album', '图集'), ('movie', '电影'), ('book', '图书'), ('book_chapter', '图书章次'), ('book_section', '图书节次')], help_text='POST类别', max_length=20, null=True, verbose_name='POST类别'),
        ),
    ]
