# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-23 16:49
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nick_name', models.CharField(default='', help_text='昵称', max_length=50, verbose_name='昵称')),
                ('name', models.CharField(blank=True, help_text='姓名', max_length=30, null=True, verbose_name='姓名')),
                ('birthday', models.DateTimeField(blank=True, help_text='生日', null=True, verbose_name='生日')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', help_text='性别', max_length=6, verbose_name='性别')),
                ('mobile', models.CharField(blank=True, help_text='电话', max_length=11, null=True, verbose_name='电话')),
                ('email', models.CharField(blank=True, help_text='邮箱', max_length=100, null=True, verbose_name='邮箱')),
                ('avatar', models.ImageField(blank=True, help_text='头像', null=True, upload_to='user/avatar/image/%Y/%m', verbose_name='头像')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': '用户',
                'verbose_name': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='验证码', max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(help_text='邮箱', max_length=50, verbose_name='邮箱')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('update_email', '修改邮箱'), ('comment', '评论')], help_text='验证码类型', max_length=15, verbose_name='验证码类型')),
                ('send_time', models.DateTimeField(auto_now_add=True, help_text='发送时间', null=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name_plural': '邮箱验证码',
                'verbose_name': '邮箱验证码',
            },
        ),
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('username', models.CharField(blank=True, help_text='用户名', max_length=50, null=True, verbose_name='用户名')),
                ('nick_name', models.CharField(default='', help_text='昵称', max_length=50, verbose_name='昵称')),
                ('mobile', models.CharField(blank=True, help_text='电话', max_length=11, null=True, verbose_name='电话')),
                ('email', models.CharField(blank=True, help_text='邮箱', max_length=100, null=True, verbose_name='邮箱')),
                ('avatar', models.ImageField(blank=True, default='user/avatar/image/guest.png', help_text='头像', null=True, upload_to='user/avatar/image/%Y/%m', verbose_name='头像')),
                ('is_subcribe', models.BooleanField(default=True, help_text='除验证码通知邮件外的通知邮件', verbose_name='是否订阅通知邮件')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '客人',
                'verbose_name': '客人',
            },
        ),
    ]
