# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-28 12:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text='用户名', max_length=50, null=True, verbose_name='用户名')),
                ('nick_name', models.CharField(default='', help_text='昵称', max_length=50, verbose_name='昵称')),
                ('mobile', models.CharField(blank=True, help_text='电话', max_length=11, null=True, verbose_name='电话')),
                ('email', models.CharField(blank=True, help_text='邮箱', max_length=100, null=True, verbose_name='邮箱')),
                ('avatar', models.ImageField(blank=True, default='user/avatar/image/guest.png', help_text='头像', null=True, upload_to='user/avatar/image/%Y/%m', verbose_name='头像')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '客人',
                'verbose_name_plural': '客人',
            },
        ),
    ]
