# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-12 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_guestprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('update_email', '修改邮箱'), ('comment', '评论')], help_text='验证码类型', max_length=15, verbose_name='验证码类型'),
        ),
    ]
