# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 06:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='icon',
            field=models.ImageField(blank=True, help_text='图标', null=True, upload_to='base/icon/%y/%m', verbose_name='图标'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='is_live',
            field=models.BooleanField(default=False, help_text='是否激活', verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='bloggerinfo',
            name='avatar',
            field=models.ImageField(blank=True, help_text='头像', null=True, upload_to='base/avatar/%y/%m', verbose_name='头像'),
        ),
    ]
