# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-16 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloggerinfo',
            old_name='name_en',
            new_name='en_name',
        ),
        migrations.RenameField(
            model_name='siteinfo',
            old_name='name_en',
            new_name='en_name',
        ),
        migrations.AddField(
            model_name='bloggerinfo',
            name='en_desc',
            field=models.CharField(default='', help_text='简介', max_length=300, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='en_desc',
            field=models.CharField(default='', help_text='英文简介', max_length=100, verbose_name='英文简介'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='en_name',
            field=models.CharField(default='', help_text='英文名称', max_length=30, verbose_name='英文名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='en_desc',
            field=models.CharField(default='', help_text='简介', max_length=150, verbose_name='简介'),
        ),
    ]
