# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-26 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggersocial',
            name='social',
            field=models.ForeignKey(help_text='社交平台', on_delete=django.db.models.deletion.CASCADE, to='material.MaterialSocial', verbose_name='社交平台'),
        ),
        migrations.AddField(
            model_name='bloggermaster',
            name='blogger',
            field=models.ForeignKey(help_text='个人', on_delete=django.db.models.deletion.CASCADE, to='base.BloggerInfo', verbose_name='个人'),
        ),
        migrations.AddField(
            model_name='bloggermaster',
            name='master',
            field=models.ForeignKey(help_text='技能', on_delete=django.db.models.deletion.CASCADE, to='material.MaterialMaster', verbose_name='技能'),
        ),
        migrations.AddField(
            model_name='bloggerinfo',
            name='masters',
            field=models.ManyToManyField(through='base.BloggerMaster', to='material.MaterialMaster'),
        ),
        migrations.AddField(
            model_name='bloggerinfo',
            name='socials',
            field=models.ManyToManyField(through='base.BloggerSocial', to='material.MaterialSocial'),
        ),
    ]
