# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-15 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='copyright_desc',
            field=models.CharField(default='', help_text='版权说明中文', max_length=300, verbose_name='版权说明中文'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='copyright_desc_en',
            field=models.CharField(default='', help_text='版权说明英文', max_length=300, verbose_name='版权说明英文'),
        ),
    ]
