# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-26 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180226_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='access_password',
            field=models.CharField(blank=True, help_text='浏览密码', max_length=20, null=True, verbose_name='访问密码'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='access_password_encrypt',
            field=models.CharField(blank=True, help_text='访问密码加密', max_length=100, null=True, verbose_name='浏览密码加密'),
        ),
    ]
