# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-12 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180112_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='navigations',
            field=models.ForeignKey(blank=True, help_text='自定义导航', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_info', to='base.NavigationLink', verbose_name='自定义导航'),
        ),
    ]
