# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20171208_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggerinfo',
            name='desc',
            field=models.CharField(default='', help_text='简介', max_length=300, verbose_name='简介'),
        ),
    ]
