# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-26 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180226_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='is_force_refresh',
            field=models.BooleanField(default=False, help_text='是否强制刷新', verbose_name='是否强制刷新'),
        ),
    ]
