# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-12 08:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180112_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfoNavigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='名称', max_length=20, verbose_name='名称')),
                ('index', models.IntegerField(default=0, help_text='顺序', verbose_name='顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('navigation', models.ForeignKey(help_text='导航', on_delete=django.db.models.deletion.CASCADE, to='base.NavigationLink', verbose_name='导航')),
            ],
            options={
                'verbose_name': '导航信息',
                'verbose_name_plural': '导航信息列表',
            },
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='navigations',
        ),
        migrations.AddField(
            model_name='siteinfonavigation',
            name='site',
            field=models.ForeignKey(help_text='网站', on_delete=django.db.models.deletion.CASCADE, to='base.SiteInfo', verbose_name='网站'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='navigations',
            field=models.ManyToManyField(help_text='自定义导航', through='base.SiteInfoNavigation', to='base.NavigationLink', verbose_name='自定义导航'),
        ),
    ]
