# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-16 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_siteinfo_is_force_refresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='api_base_url',
            field=models.URLField(default='https://blog.coderap.com/api', max_length=30, verbose_name='API接口BaseURL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloggerinfo',
            name='avatar',
            field=models.ImageField(blank=True, help_text='100*100', null=True, upload_to='base/avatar/image/%y/%m', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='bloggerinfo',
            name='background',
            field=models.ImageField(blank=True, help_text='333*125', null=True, upload_to='base/background/image/%y/%m', verbose_name='背景图'),
        ),
    ]
