# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_friendlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggerinfo',
            name='background',
            field=models.ImageField(blank=True, help_text='背景图', null=True, upload_to='base/background/%y/%m', verbose_name='背景图'),
        ),
    ]
