# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-14 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20180316_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlink',
            name='url',
            field=models.CharField(help_text='链接', max_length=200, verbose_name='链接'),
        ),
    ]
