# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-29 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_navigationlink_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='keywords',
            field=models.CharField(default='', help_text='关键字', max_length=300, verbose_name='关键字'),
        ),
    ]
