# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-05 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_siteinfo_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='desc',
            field=models.CharField(default='', help_text='简介', max_length=150, verbose_name='简介'),
        ),
    ]
