# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-23 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QiniuTokenRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(help_text='请求者IP', verbose_name='请求者IP')),
                ('token', models.CharField(help_text='token', max_length=512, verbose_name='token')),
                ('use_type', models.CharField(choices=[('comment', '评论')], help_text='使用类型', max_length=15, verbose_name='使用类型')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='发送时间', verbose_name='发送时间')),
            ],
            options={
                'verbose_name_plural': '七牛云请求Token',
                'verbose_name': '七牛云请求Token',
            },
        ),
    ]
