# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20180116_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qiniutokenrecord',
            name='token',
            field=models.CharField(help_text='token', max_length=512, verbose_name='token'),
        ),
    ]
