# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-17 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetail',
            name='language',
            field=models.CharField(blank=True, choices=[('CN', '中文'), ('EN', 'English')], help_text='现暂时提供两种语言类别', max_length=5, null=True, verbose_name='文章详情语言类别'),
        ),
    ]
