# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_content', models.TextField(help_text='原始内容', verbose_name='原始内容')),
                ('formatted_content', models.TextField(help_text='处理后内容', verbose_name='处理后内容')),
            ],
            options={
                'verbose_name': '电影详情',
                'verbose_name_plural': '电影详情列表',
            },
        ),
        migrations.RemoveField(
            model_name='movieinfo',
            name='formatted_content',
        ),
        migrations.RemoveField(
            model_name='movieinfo',
            name='origin_content',
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='movie_info',
            field=models.OneToOneField(blank=True, help_text='内容', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='movie.MovieInfo', verbose_name='内容'),
        ),
    ]
