# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movietag',
            options={'verbose_name': '电影标签', 'verbose_name_plural': '电影标签'},
        ),
    ]
