# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movieinfo_post_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieinfo',
            options={'verbose_name': '电影', 'verbose_name_plural': '电影列表'},
        ),
        migrations.RemoveField(
            model_name='movieinfo',
            name='post_type',
        ),
    ]
