# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleInfo',
            fields=[
                ('postbaseinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='material.PostBaseInfo')),
                ('origin_content', models.TextField(help_text='原始内容', verbose_name='原始内容')),
                ('formatted_content', models.TextField(help_text='处理后内容', verbose_name='处理后内容')),
            ],
            options={
                'verbose_name': '文章基本信息',
                'verbose_name_plural': '文章基本信息',
            },
            bases=('material.postbaseinfo',),
        ),
    ]
