# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-23 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_content', models.TextField(help_text='原始内容', verbose_name='原始内容')),
                ('formatted_content', models.TextField(help_text='处理后内容', verbose_name='处理后内容')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name_plural': '文章详情列表',
                'verbose_name': '文章详情',
            },
        ),
        migrations.CreateModel(
            name='ArticleInfo',
            fields=[
                ('postbaseinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='material.PostBaseInfo')),
            ],
            options={
                'verbose_name_plural': '文章列表',
                'verbose_name': '文章',
            },
            bases=('material.postbaseinfo',),
        ),
        migrations.AddField(
            model_name='articledetail',
            name='article_info',
            field=models.ForeignKey(blank=True, help_text='内容', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='article.ArticleInfo', verbose_name='内容'),
        ),
    ]
