# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-16 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articledetail_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='language',
            field=models.CharField(blank=True, choices=[('中文', '中文'), ('EN', 'English')], default='cn', help_text='现暂时提供两种语言类别，默认为中文', max_length=5, null=True, verbose_name='文章详情语言类别'),
        ),
    ]
