# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20171223_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='article_info',
            field=models.OneToOneField(blank=True, help_text='内容', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='article.ArticleInfo', verbose_name='内容'),
        ),
    ]
