# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articledetail_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='title',
            field=models.CharField(help_text='标题', max_length=100, verbose_name='标题'),
        ),
    ]
